FROM prefecthq/prefect:2-python3.10

RUN pip install --upgrade pip setuptools --no-cache-dir
RUN pip install poetry==1.3.2

COPY pyproject.toml ./
COPY poetry.lock ./

RUN poetry export -f requirements.txt -o requirements.txt
RUN pip install -r requirements.txt

ARG PREFECT_API_KEY
ENV PREFECT_API_KEY=$PREFECT_API_KEY

ARG PREFECT_API_URL
ENV PREFECT_API_URL=$PREFECT_API_URL

ENV PYTHONUNBUFFERED True

WORKDIR app

COPY src/ ./